### ISSUE TITLE
Remove deprecated provider option "clone_wait"

### ISSUE THREAD

**Issue by shamuraix** [sdhibit/terraform-proxmox-cloud-init-vm#5]
The Telmate Proxmox provider has deprecated "clone_wait" and instead the api should manage timeouts. Please see link below for provider documentation.

https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#clone_wait

**Comment by sdhibit** [comment]
Removed in PR #7
